name: 'YC Function deploy (with storage mount support)'
description: 'GitHub Action to deploy Serverless Function to Yandex Cloud.'
author: 'Nikolay Matrosov'
inputs:
  yc-sa-json-credentials:
    required: true
    description: 'Json containing authorized key for Service Account. More info https://cloud.yandex.ru/docs/container-registry/operations/authentication#sa-json'
  folder-id:
    required: true
    description: 'Folder ID'
  function-name:
    description: 'Function Name'
    default: ''
    required: true
  bucket:
    description: 'Object Storage bucket name for code'
    default: ''
    required: false
  runtime:
    description: 'Runtime for function.'
    default: ''
    required: true
  entrypoint:
    description: 'Entrypoint for function'
    default: ''
    required: true
  include:
    description: 'Source directories for cloud function in git repo. Multiline'
    default: '.'
    required: false
  exclude:
    description: 'Exclude patterns for source directory. Multiline'
    default: ''
    required: false
  source-root:
    description: 'Path that will considered as function source root.'
    required: false
    default: '.'
  memory:
    description: 'Memory in Mb. Pattern: ^\d+Mb$'
    default: '128Mb'
    required: false
  environment:
    description: 'Env variables for function. Multiline'
    default: ''
    required: false
  execution-timeout:
    description: 'Execution timeout in seconds'
    default: '5'
    required: false
  service-account:
    description: 'Service account for function'
    default: ''
    required: false
  secrets:
    description: 'Lockbox secrets. Pattern: "<environmentVariable>=<secretId>/<versionId>/<secretKey>". Multiline'
    default: ''
    required: false
  network-id:
    description: 'Function version connectivity. If specified the version will be attached to specified network/subnet(s).'
    default: ''
    required: false
  tags:
    description: 'Version tags. Multiline'
    default: ''
    required: false
  logs-disabled:
    description: 'Disable functions logging. Default false'
    default: 'false'
    required: false
  logs-group-id:
    description: 'Logs group ID. If NOT set, logs will write to auto-created default group.'
    default: ''
    required: false
  log-level:
    description: 'Minimum log level (trace, debug, info, warn, error, fatal)'
    default: ''
    required: false
  mount-bucket-id:
    description: 'Object Storage bucket id for mount'
    default: ''
    required: false
  mount-bucket-path:
    description: 'Path to the folder in the Object Storage bucket. Leave empty to mount the entire bucket'
    default: ''
    required: false
  mount-point:
    description: 'Mount point is used to create a directory where the bucket/folder will be mounted. It will be accessible at the path /function/storage/<mount-point>'
    default: ''
    required: false
  mount-read-only:
    description: 'Read-only mount mode. Default true'
    default: 'true'
    required: false


outputs:
  function-id:
    description: 'Function ID.'
  version-id:
    description: 'ID of the newly created function version.'

branding:
  color: blue
  icon: code
runs:
  using: 'node20'
  main: 'dist/index.js'
